### ISSUE TITLE
Behold Him Chords

### ISSUE THREAD

**Issue by mattgraham** [mattgraham/worship#20]
[song started here](https://github.com/mattgraham/worship/blob/master/Behold%20Him.onsong)

**Comment by mattgraham** [comment]
@rkornacki https://open.spotify.com/track/0VlVeykJp1Vocxjk2LtXU1 I've not found these chords on the web as of yet; might need a look.

**Comment by mattgraham** [comment]
@rkornacki my best guess so far is:

Guitar Intro: (Slide)
Am  Bm7  C   D   Em

Verse: 
Am

Chorus: 
Am    C   D   Em

Bridge: 
 Am   Bm7  C  Em

**Comment by rkornacki** [comment]
Hey Matt,

Not sure on the intro… they hold the “A” on the lowest string, and slide up using “Am”, “G” or “Bm”, “C”, or one guitar plays an “Am” while another guitar plays a lead that follows the melody from the verse...

But here’s what I got for the rest:

Verse: “Am" like you said

Chorus: “Am” to “F” (or “Fmaj7”) to “Dm7” to “Esus” to “E” or “Em” (not sure)

Bridge: “Am” to “G” (or “G6” if you want a little color) to “F” (or “Fmaj7”), to “Esus”

I like the song, neat feel to it:)

Rob

**Comment by mattgraham** [comment]
Awesome. Love it;  I do think you're missing the Dm7 in the guitar slide progression but the rest sounds great on the guitar as well. Thanks!

**Comment by mattgraham** [comment]
I beleve this is all set; at least for the beta testing round.
